//! Extended catalog of ~80 popular terminal colour schemes.
//!
//! These are merged into [`crate::theme::builtin_themes`] at runtime.
//! Existing themes (defined directly in `theme.rs`) take precedence over any
//! catalog entry with the same name.

use crate::theme::Theme;

/// Returns all catalog themes. Accurate hex palettes sourced from each
/// theme's official repository / specification.
#[must_use]
pub fn catalog_themes() -> Vec<Theme> {
    vec![
        // ── Gruvbox ───────────────────────────────────────────────────────────
        Theme {
            name: "Gruvbox Light".into(),
            background: "#fbf1c7".into(),
            foreground: "#3c3836".into(),
            cursor: "#af3a03".into(),
            selection: "#d5c4a1".into(),
            normal: [
                "#fbf1c7".into(),
                "#cc241d".into(),
                "#98971a".into(),
                "#d79921".into(),
                "#458588".into(),
                "#b16286".into(),
                "#689d6a".into(),
                "#7c6f64".into(),
            ],
            bright: [
                "#928374".into(),
                "#9d0006".into(),
                "#79740e".into(),
                "#b57614".into(),
                "#076678".into(),
                "#8f3f71".into(),
                "#427b58".into(),
                "#3c3836".into(),
            ],
        },
        // ── Solarized ─────────────────────────────────────────────────────────
        Theme {
            name: "Solarized Light".into(),
            background: "#fdf6e3".into(),
            foreground: "#657b83".into(),
            cursor: "#586e75".into(),
            selection: "#eee8d5".into(),
            normal: [
                "#073642".into(),
                "#dc322f".into(),
                "#859900".into(),
                "#b58900".into(),
                "#268bd2".into(),
                "#d33682".into(),
                "#2aa198".into(),
                "#eee8d5".into(),
            ],
            bright: [
                "#002b36".into(),
                "#cb4b16".into(),
                "#586e75".into(),
                "#657b83".into(),
                "#839496".into(),
                "#6c71c4".into(),
                "#93a1a1".into(),
                "#fdf6e3".into(),
            ],
        },
        // ── Catppuccin ────────────────────────────────────────────────────────
        Theme {
            name: "Catppuccin Frappe".into(),
            background: "#303446".into(),
            foreground: "#c6d0f5".into(),
            cursor: "#f2d5cf".into(),
            selection: "#626880".into(),
            normal: [
                "#51576d".into(),
                "#e78284".into(),
                "#a6d189".into(),
                "#e5c890".into(),
                "#8caaee".into(),
                "#f4b8e4".into(),
                "#81c8be".into(),
                "#b5bfe2".into(),
            ],
            bright: [
                "#626880".into(),
                "#e78284".into(),
                "#a6d189".into(),
                "#e5c890".into(),
                "#8caaee".into(),
                "#f4b8e4".into(),
                "#81c8be".into(),
                "#a5adce".into(),
            ],
        },
        Theme {
            name: "Catppuccin Macchiato".into(),
            background: "#24273a".into(),
            foreground: "#cad3f5".into(),
            cursor: "#f4dbd6".into(),
            selection: "#5b6078".into(),
            normal: [
                "#494d64".into(),
                "#ed8796".into(),
                "#a6da95".into(),
                "#eed49f".into(),
                "#8aadf4".into(),
                "#f5bde6".into(),
                "#8bd5ca".into(),
                "#b8c0e0".into(),
            ],
            bright: [
                "#5b6078".into(),
                "#ed8796".into(),
                "#a6da95".into(),
                "#eed49f".into(),
                "#8aadf4".into(),
                "#f5bde6".into(),
                "#8bd5ca".into(),
                "#a5adcb".into(),
            ],
        },
        // ── One Dark / One Light ──────────────────────────────────────────────
        Theme {
            name: "One Light".into(),
            background: "#fafafa".into(),
            foreground: "#383a42".into(),
            cursor: "#526fff".into(),
            selection: "#d0d1d4".into(),
            normal: [
                "#383a42".into(),
                "#e45649".into(),
                "#50a14f".into(),
                "#c18401".into(),
                "#0184bc".into(),
                "#a626a4".into(),
                "#0997b3".into(),
                "#fafafa".into(),
            ],
            bright: [
                "#4f525e".into(),
                "#e45649".into(),
                "#50a14f".into(),
                "#c18401".into(),
                "#0184bc".into(),
                "#a626a4".into(),
                "#0997b3".into(),
                "#ffffff".into(),
            ],
        },
        // ── Monokai ───────────────────────────────────────────────────────────
        Theme {
            name: "Monokai Pro".into(),
            background: "#2d2a2e".into(),
            foreground: "#fcfcfa".into(),
            cursor: "#fcfcfa".into(),
            selection: "#403e41".into(),
            normal: [
                "#403e41".into(),
                "#ff6188".into(),
                "#a9dc76".into(),
                "#ffd866".into(),
                "#fc9867".into(),
                "#ab9df2".into(),
                "#78dce8".into(),
                "#fcfcfa".into(),
            ],
            bright: [
                "#727072".into(),
                "#ff6188".into(),
                "#a9dc76".into(),
                "#ffd866".into(),
                "#fc9867".into(),
                "#ab9df2".into(),
                "#78dce8".into(),
                "#fcfcfa".into(),
            ],
        },
        Theme {
            name: "Monokai Classic".into(),
            background: "#272822".into(),
            foreground: "#f8f8f2".into(),
            cursor: "#f8f8f0".into(),
            selection: "#49483e".into(),
            normal: [
                "#272822".into(),
                "#f92672".into(),
                "#a6e22e".into(),
                "#f4bf75".into(),
                "#66d9e8".into(),
                "#ae81ff".into(),
                "#a1efe4".into(),
                "#f8f8f2".into(),
            ],
            bright: [
                "#75715e".into(),
                "#f92672".into(),
                "#a6e22e".into(),
                "#f4bf75".into(),
                "#66d9e8".into(),
                "#ae81ff".into(),
                "#a1efe4".into(),
                "#f9f8f5".into(),
            ],
        },
        // ── Tomorrow Night ────────────────────────────────────────────────────
        Theme {
            name: "Tomorrow Night".into(),
            background: "#1d1f21".into(),
            foreground: "#c5c8c6".into(),
            cursor: "#aeafad".into(),
            selection: "#373b41".into(),
            normal: [
                "#1d1f21".into(),
                "#cc6666".into(),
                "#b5bd68".into(),
                "#f0c674".into(),
                "#81a2be".into(),
                "#b294bb".into(),
                "#8abeb7".into(),
                "#c5c8c6".into(),
            ],
            bright: [
                "#666666".into(),
                "#d54e53".into(),
                "#b9ca4a".into(),
                "#e7c547".into(),
                "#7aa6da".into(),
                "#c397d8".into(),
                "#70c0b1".into(),
                "#eaeaea".into(),
            ],
        },
        Theme {
            name: "Tomorrow Night Blue".into(),
            background: "#002451".into(),
            foreground: "#ffffff".into(),
            cursor: "#ffffff".into(),
            selection: "#003f8e".into(),
            normal: [
                "#00346e".into(),
                "#ff9da4".into(),
                "#d1f1a9".into(),
                "#ffeead".into(),
                "#bbdaff".into(),
                "#ebbbff".into(),
                "#99ffff".into(),
                "#ffffff".into(),
            ],
            bright: [
                "#003f8e".into(),
                "#ff9da4".into(),
                "#d1f1a9".into(),
                "#ffeead".into(),
                "#bbdaff".into(),
                "#ebbbff".into(),
                "#99ffff".into(),
                "#ffffff".into(),
            ],
        },
        Theme {
            name: "Tomorrow Night Eighties".into(),
            background: "#2d2d2d".into(),
            foreground: "#cccccc".into(),
            cursor: "#cccccc".into(),
            selection: "#515151".into(),
            normal: [
                "#2d2d2d".into(),
                "#f2777a".into(),
                "#99cc99".into(),
                "#ffcc66".into(),
                "#6699cc".into(),
                "#cc99cc".into(),
                "#66cccc".into(),
                "#cccccc".into(),
            ],
            bright: [
                "#999999".into(),
                "#f2777a".into(),
                "#99cc99".into(),
                "#ffcc66".into(),
                "#6699cc".into(),
                "#cc99cc".into(),
                "#66cccc".into(),
                "#ffffff".into(),
            ],
        },
        // ── Ayu ───────────────────────────────────────────────────────────────
        Theme {
            name: "Ayu Mirage".into(),
            background: "#1f2430".into(),
            foreground: "#cbccc6".into(),
            cursor: "#ffcc66".into(),
            selection: "#34455a".into(),
            normal: [
                "#191e2a".into(),
                "#ff3333".into(),
                "#bae67e".into(),
                "#ffd580".into(),
                "#73d0ff".into(),
                "#d4bfff".into(),
                "#95e6cb".into(),
                "#c7c7c7".into(),
            ],
            bright: [
                "#686868".into(),
                "#ff3333".into(),
                "#bae67e".into(),
                "#ffd580".into(),
                "#73d0ff".into(),
                "#d4bfff".into(),
                "#95e6cb".into(),
                "#ffffff".into(),
            ],
        },
        Theme {
            name: "Ayu Light".into(),
            background: "#fafafa".into(),
            foreground: "#575f66".into(),
            cursor: "#ff6a00".into(),
            selection: "#d4d8de".into(),
            normal: [
                "#000000".into(),
                "#ff3333".into(),
                "#86b300".into(),
                "#f29718".into(),
                "#41a6d9".into(),
                "#f07171".into(),
                "#4cbf99".into(),
                "#d9d8d7".into(),
            ],
            bright: [
                "#323232".into(),
                "#ff3333".into(),
                "#86b300".into(),
                "#f29718".into(),
                "#41a6d9".into(),
                "#f07171".into(),
                "#4cbf99".into(),
                "#ffffff".into(),
            ],
        },
        // ── Material ──────────────────────────────────────────────────────────
        Theme {
            name: "Material Dark".into(),
            background: "#212121".into(),
            foreground: "#eeffff".into(),
            cursor: "#ffcc00".into(),
            selection: "#80cbc4".into(),
            normal: [
                "#212121".into(),
                "#f07178".into(),
                "#c3e88d".into(),
                "#ffcb6b".into(),
                "#82aaff".into(),
                "#c792ea".into(),
                "#89ddff".into(),
                "#ffffff".into(),
            ],
            bright: [
                "#546e7a".into(),
                "#ff5370".into(),
                "#c3e88d".into(),
                "#f78c6c".into(),
                "#82aaff".into(),
                "#c792ea".into(),
                "#89ddff".into(),
                "#eeffff".into(),
            ],
        },
        Theme {
            name: "Material Ocean".into(),
            background: "#0f111a".into(),
            foreground: "#8f93a2".into(),
            cursor: "#ffcc00".into(),
            selection: "#1c3a5e".into(),
            normal: [
                "#090b10".into(),
                "#f07178".into(),
                "#c3e88d".into(),
                "#ffcb6b".into(),
                "#82aaff".into(),
                "#c792ea".into(),
                "#89ddff".into(),
                "#ffffff".into(),
            ],
            bright: [
                "#464b5d".into(),
                "#ff5370".into(),
                "#c3e88d".into(),
                "#f78c6c".into(),
                "#82aaff".into(),
                "#c792ea".into(),
                "#89ddff".into(),
                "#eeffff".into(),
            ],
        },
        // ── Night Owl ─────────────────────────────────────────────────────────
        Theme {
            name: "Night Owl".into(),
            background: "#011627".into(),
            foreground: "#d6deeb".into(),
            cursor: "#80a4c2".into(),
            selection: "#1d3b53".into(),
            normal: [
                "#1d3b53".into(),
                "#fc514e".into(),
                "#22da6e".into(),
                "#addb67".into(),
                "#82aaff".into(),
                "#c792ea".into(),
                "#21c7a8".into(),
                "#ffffff".into(),
            ],
            bright: [
                "#7fdbca".into(),
                "#ff5874".into(),
                "#21c7a8".into(),
                "#ecc48d".into(),
                "#82aaff".into(),
                "#ae81ff".into(),
                "#7fdbca".into(),
                "#ffffff".into(),
            ],
        },
        Theme {
            name: "Night Owl Light".into(),
            background: "#fbfbfb".into(),
            foreground: "#403f53".into(),
            cursor: "#403f53".into(),
            selection: "#e0e0e0".into(),
            normal: [
                "#011627".into(),
                "#d3423e".into(),
                "#2aa298".into(),
                "#daaa01".into(),
                "#4876d6".into(),
                "#403f53".into(),
                "#08916a".into(),
                "#7a8181".into(),
            ],
            bright: [
                "#7a8181".into(),
                "#d3423e".into(),
                "#2aa298".into(),
                "#daaa01".into(),
                "#4876d6".into(),
                "#403f53".into(),
                "#08916a".into(),
                "#403f53".into(),
            ],
        },
        // ── Palenight ─────────────────────────────────────────────────────────
        Theme {
            name: "Palenight".into(),
            background: "#292d3e".into(),
            foreground: "#a6accd".into(),
            cursor: "#ffcb6b".into(),
            selection: "#3c435e".into(),
            normal: [
                "#292d3e".into(),
                "#f07178".into(),
                "#c3e88d".into(),
                "#ffcb6b".into(),
                "#82aaff".into(),
                "#c792ea".into(),
                "#89ddff".into(),
                "#d0d0d0".into(),
            ],
            bright: [
                "#434758".into(),
                "#ff8b92".into(),
                "#ddffa7".into(),
                "#ffe585".into(),
                "#9cc4ff".into(),
                "#e1acff".into(),
                "#a3f7ff".into(),
                "#ffffff".into(),
            ],
        },
        // ── Oceanic Next ──────────────────────────────────────────────────────
        Theme {
            name: "Oceanic Next".into(),
            background: "#1b2b34".into(),
            foreground: "#d8dee9".into(),
            cursor: "#c0c5ce".into(),
            selection: "#4f5b66".into(),
            normal: [
                "#1b2b34".into(),
                "#ec5f67".into(),
                "#99c794".into(),
                "#fac863".into(),
                "#6699cc".into(),
                "#c594c5".into(),
                "#5fb3b3".into(),
                "#c0c5ce".into(),
            ],
            bright: [
                "#65737e".into(),
                "#ec5f67".into(),
                "#99c794".into(),
                "#fac863".into(),
                "#6699cc".into(),
                "#c594c5".into(),
                "#5fb3b3".into(),
                "#d8dee9".into(),
            ],
        },
        // ── Snazzy ────────────────────────────────────────────────────────────
        Theme {
            name: "Snazzy".into(),
            background: "#282a36".into(),
            foreground: "#eff0eb".into(),
            cursor: "#97979b".into(),
            selection: "#3e404a".into(),
            normal: [
                "#282a36".into(),
                "#ff5c57".into(),
                "#5af78e".into(),
                "#f3f99d".into(),
                "#57c7ff".into(),
                "#ff6ac1".into(),
                "#9aedfe".into(),
                "#f1f1f0".into(),
            ],
            bright: [
                "#686868".into(),
                "#ff5c57".into(),
                "#5af78e".into(),
                "#f3f99d".into(),
                "#57c7ff".into(),
                "#ff6ac1".into(),
                "#9aedfe".into(),
                "#eff0eb".into(),
            ],
        },
        // ── Cobalt2 ───────────────────────────────────────────────────────────
        Theme {
            name: "Cobalt2".into(),
            background: "#132738".into(),
            foreground: "#ffffff".into(),
            cursor: "#f0f50f".into(),
            selection: "#18354f".into(),
            normal: [
                "#000000".into(),
                "#ff0000".into(),
                "#38de21".into(),
                "#ffe50a".into(),
                "#1460d2".into(),
                "#ff005d".into(),
                "#00bbbb".into(),
                "#bbbbbb".into(),
            ],
            bright: [
                "#555555".into(),
                "#f40e17".into(),
                "#3bd01d".into(),
                "#edc809".into(),
                "#5555ff".into(),
                "#ff55ff".into(),
                "#6ae3fa".into(),
                "#ffffff".into(),
            ],
        },
        // ── Horizon ───────────────────────────────────────────────────────────
        Theme {
            name: "Horizon Dark".into(),
            background: "#1c1e26".into(),
            foreground: "#d5d8da".into(),
            cursor: "#e95678".into(),
            selection: "#232530".into(),
            normal: [
                "#16161c".into(),
                "#e95678".into(),
                "#29d398".into(),
                "#fab795".into(),
                "#26bbd9".into(),
                "#ee64ac".into(),
                "#59e3e3".into(),
                "#d5d8da".into(),
            ],
            bright: [
                "#414558".into(),
                "#ec6a88".into(),
                "#3fdaa4".into(),
                "#fbc3a7".into(),
                "#3fc6de".into(),
                "#f075b5".into(),
                "#6be6e6".into(),
                "#d5d8da".into(),
            ],
        },
        // ── Everforest ────────────────────────────────────────────────────────
        Theme {
            name: "Everforest Dark".into(),
            background: "#2d353b".into(),
            foreground: "#d3c6aa".into(),
            cursor: "#d3c6aa".into(),
            selection: "#475258".into(),
            normal: [
                "#475258".into(),
                "#e67e80".into(),
                "#a7c080".into(),
                "#dbbc7f".into(),
                "#7fbbb3".into(),
                "#d699b6".into(),
                "#83c092".into(),
                "#d3c6aa".into(),
            ],
            bright: [
                "#5c6a72".into(),
                "#e67e80".into(),
                "#a7c080".into(),
                "#dbbc7f".into(),
                "#7fbbb3".into(),
                "#d699b6".into(),
                "#83c092".into(),
                "#d3c6aa".into(),
            ],
        },
        Theme {
            name: "Everforest Light".into(),
            background: "#fdf6e3".into(),
            foreground: "#5c6a72".into(),
            cursor: "#5c6a72".into(),
            selection: "#efebd4".into(),
            normal: [
                "#5c6a72".into(),
                "#f85552".into(),
                "#8da101".into(),
                "#dfa000".into(),
                "#3a94c5".into(),
                "#df69ba".into(),
                "#35a77c".into(),
                "#dfddc8".into(),
            ],
            bright: [
                "#a6b0a0".into(),
                "#f85552".into(),
                "#8da101".into(),
                "#dfa000".into(),
                "#3a94c5".into(),
                "#df69ba".into(),
                "#35a77c".into(),
                "#5c6a72".into(),
            ],
        },
        // ── Rosé Pine variants ────────────────────────────────────────────────
        Theme {
            name: "Rosé Pine Moon".into(),
            background: "#232136".into(),
            foreground: "#e0def4".into(),
            cursor: "#ea9a97".into(),
            selection: "#393552".into(),
            normal: [
                "#2a273f".into(),
                "#eb6f92".into(),
                "#3e8fb0".into(),
                "#f6c177".into(),
                "#9ccfd8".into(),
                "#c4a7e7".into(),
                "#ea9a97".into(),
                "#e0def4".into(),
            ],
            bright: [
                "#6e6a86".into(),
                "#eb6f92".into(),
                "#3e8fb0".into(),
                "#f6c177".into(),
                "#9ccfd8".into(),
                "#c4a7e7".into(),
                "#ea9a97".into(),
                "#e0def4".into(),
            ],
        },
        Theme {
            name: "Rosé Pine Dawn".into(),
            background: "#faf4ed".into(),
            foreground: "#575279".into(),
            cursor: "#907aa9".into(),
            selection: "#dfdad9".into(),
            normal: [
                "#f2e9e1".into(),
                "#b4637a".into(),
                "#286983".into(),
                "#ea9d34".into(),
                "#56949f".into(),
                "#907aa9".into(),
                "#d7827e".into(),
                "#575279".into(),
            ],
            bright: [
                "#9893a5".into(),
                "#b4637a".into(),
                "#286983".into(),
                "#ea9d34".into(),
                "#56949f".into(),
                "#907aa9".into(),
                "#d7827e".into(),
                "#575279".into(),
            ],
        },
        // ── GitHub ────────────────────────────────────────────────────────────
        Theme {
            name: "GitHub Dark".into(),
            background: "#0d1117".into(),
            foreground: "#e6edf3".into(),
            cursor: "#58a6ff".into(),
            selection: "#1f2d3d".into(),
            normal: [
                "#484f58".into(),
                "#ff7b72".into(),
                "#3fb950".into(),
                "#d29922".into(),
                "#58a6ff".into(),
                "#bc8cff".into(),
                "#39c5cf".into(),
                "#b1bac4".into(),
            ],
            bright: [
                "#6e7681".into(),
                "#ffa198".into(),
                "#56d364".into(),
                "#e3b341".into(),
                "#79c0ff".into(),
                "#d2a8ff".into(),
                "#56d4dd".into(),
                "#f0f6fc".into(),
            ],
        },
        Theme {
            name: "GitHub Light".into(),
            background: "#ffffff".into(),
            foreground: "#24292f".into(),
            cursor: "#0969da".into(),
            selection: "#e8f3ff".into(),
            normal: [
                "#24292f".into(),
                "#cf222e".into(),
                "#116329".into(),
                "#4d2d00".into(),
                "#0969da".into(),
                "#8250df".into(),
                "#1b7c83".into(),
                "#6e7781".into(),
            ],
            bright: [
                "#57606a".into(),
                "#a40e26".into(),
                "#1a7f37".into(),
                "#633c01".into(),
                "#218bff".into(),
                "#a475f9".into(),
                "#3192aa".into(),
                "#8c959f".into(),
            ],
        },
        // ── Kanagawa ──────────────────────────────────────────────────────────
        Theme {
            name: "Kanagawa Wave".into(),
            background: "#1f1f28".into(),
            foreground: "#dcd7ba".into(),
            cursor: "#c8c093".into(),
            selection: "#2d4f67".into(),
            normal: [
                "#16161d".into(),
                "#c34043".into(),
                "#76946a".into(),
                "#c0a36e".into(),
                "#7e9cd8".into(),
                "#957fb8".into(),
                "#6a9589".into(),
                "#c8c093".into(),
            ],
            bright: [
                "#727169".into(),
                "#e82424".into(),
                "#98bb6c".into(),
                "#e6c384".into(),
                "#7fb4ca".into(),
                "#938aa9".into(),
                "#7aa89f".into(),
                "#dcd7ba".into(),
            ],
        },
        Theme {
            name: "Kanagawa Dragon".into(),
            background: "#181616".into(),
            foreground: "#c5c9c5".into(),
            cursor: "#c8c093".into(),
            selection: "#2d4f67".into(),
            normal: [
                "#0d0c0c".into(),
                "#c4746e".into(),
                "#8a9a7b".into(),
                "#c4b28a".into(),
                "#8ba4b0".into(),
                "#a292a3".into(),
                "#8ea4a2".into(),
                "#c8c093".into(),
            ],
            bright: [
                "#a6a69c".into(),
                "#e46876".into(),
                "#87a987".into(),
                "#e6c384".into(),
                "#7fb4ca".into(),
                "#938aa9".into(),
                "#7aa89f".into(),
                "#dcd7ba".into(),
            ],
        },
        // ── Tokyonight Day ────────────────────────────────────────────────────
        Theme {
            name: "Tokyo Night Day".into(),
            background: "#e1e2e7".into(),
            foreground: "#3760bf".into(),
            cursor: "#3760bf".into(),
            selection: "#b4c2f0".into(),
            normal: [
                "#e9e9ed".into(),
                "#f52a65".into(),
                "#587539".into(),
                "#8c6c3e".into(),
                "#2e7de9".into(),
                "#9854f1".into(),
                "#007197".into(),
                "#6172b0".into(),
            ],
            bright: [
                "#a1a6c5".into(),
                "#f52a65".into(),
                "#587539".into(),
                "#8c6c3e".into(),
                "#2e7de9".into(),
                "#9854f1".into(),
                "#007197".into(),
                "#3760bf".into(),
            ],
        },
        // ── Poimandres ────────────────────────────────────────────────────────
        Theme {
            name: "Poimandres".into(),
            background: "#1b1e28".into(),
            foreground: "#a6accd".into(),
            cursor: "#89ddff".into(),
            selection: "#303340".into(),
            normal: [
                "#1b1e28".into(),
                "#d0679d".into(),
                "#5de4c7".into(),
                "#fffac2".into(),
                "#89ddff".into(),
                "#fcc5e9".into(),
                "#add7ff".into(),
                "#ffffff".into(),
            ],
            bright: [
                "#a6accd".into(),
                "#d0679d".into(),
                "#5de4c7".into(),
                "#fffac2".into(),
                "#89ddff".into(),
                "#fcc5e9".into(),
                "#add7ff".into(),
                "#ffffff".into(),
            ],
        },
        // ── Mellow ────────────────────────────────────────────────────────────
        Theme {
            name: "Mellow".into(),
            background: "#1e2022".into(),
            foreground: "#c6c8d1".into(),
            cursor: "#c6c8d1".into(),
            selection: "#2a2d2f".into(),
            normal: [
                "#1a1d1e".into(),
                "#e06c75".into(),
                "#98c379".into(),
                "#e5c07b".into(),
                "#61afef".into(),
                "#c678dd".into(),
                "#56b6c2".into(),
                "#abb2bf".into(),
            ],
            bright: [
                "#5c6370".into(),
                "#e06c75".into(),
                "#98c379".into(),
                "#e5c07b".into(),
                "#61afef".into(),
                "#c678dd".into(),
                "#56b6c2".into(),
                "#ffffff".into(),
            ],
        },
        // ── Melange ───────────────────────────────────────────────────────────
        Theme {
            name: "Melange Dark".into(),
            background: "#352a23".into(),
            foreground: "#ece1d7".into(),
            cursor: "#ece1d7".into(),
            selection: "#4d3b2e".into(),
            normal: [
                "#34302c".into(),
                "#b65c60".into(),
                "#78997a".into(),
                "#b5a16d".into(),
                "#7f91b2".into(),
                "#b380b0".into(),
                "#7aaca9".into(),
                "#a38d78".into(),
            ],
            bright: [
                "#7c6f62".into(),
                "#d47766".into(),
                "#84a98c".into(),
                "#d9b27c".into(),
                "#9aafe2".into(),
                "#cf9bc2".into(),
                "#87c8c4".into(),
                "#ece1d7".into(),
            ],
        },
        // ── Vesper ────────────────────────────────────────────────────────────
        Theme {
            name: "Vesper".into(),
            background: "#101010".into(),
            foreground: "#ffffff".into(),
            cursor: "#ff9966".into(),
            selection: "#1f1f1f".into(),
            normal: [
                "#101010".into(),
                "#e06c75".into(),
                "#5affb3".into(),
                "#ffc799".into(),
                "#7eb3f0".into(),
                "#cc99ff".into(),
                "#66d9ef".into(),
                "#bbbbbb".into(),
            ],
            bright: [
                "#555555".into(),
                "#ff9966".into(),
                "#90ee90".into(),
                "#ffe0b3".into(),
                "#99c5f5".into(),
                "#ddbbff".into(),
                "#99e6f5".into(),
                "#ffffff".into(),
            ],
        },
        // ── Flexoki ───────────────────────────────────────────────────────────
        Theme {
            name: "Flexoki Dark".into(),
            background: "#100f0f".into(),
            foreground: "#cecdc3".into(),
            cursor: "#d0a215".into(),
            selection: "#282726".into(),
            normal: [
                "#282726".into(),
                "#af3029".into(),
                "#66800b".into(),
                "#ad8301".into(),
                "#205ea6".into(),
                "#5c4a72".into(),
                "#24837b".into(),
                "#b7b5ac".into(),
            ],
            bright: [
                "#575653".into(),
                "#d14d41".into(),
                "#879a39".into(),
                "#d0a215".into(),
                "#4385be".into(),
                "#8b7ec8".into(),
                "#3aa99f".into(),
                "#cecdc3".into(),
            ],
        },
        Theme {
            name: "Flexoki Light".into(),
            background: "#fffcf0".into(),
            foreground: "#100f0f".into(),
            cursor: "#24837b".into(),
            selection: "#e6e4d9".into(),
            normal: [
                "#e6e4d9".into(),
                "#af3029".into(),
                "#66800b".into(),
                "#ad8301".into(),
                "#205ea6".into(),
                "#5c4a72".into(),
                "#24837b".into(),
                "#6f6e69".into(),
            ],
            bright: [
                "#b7b5ac".into(),
                "#d14d41".into(),
                "#879a39".into(),
                "#d0a215".into(),
                "#4385be".into(),
                "#8b7ec8".into(),
                "#3aa99f".into(),
                "#100f0f".into(),
            ],
        },
        // ── Doom One ──────────────────────────────────────────────────────────
        Theme {
            name: "Doom One".into(),
            background: "#282c34".into(),
            foreground: "#bbc2cf".into(),
            cursor: "#528bff".into(),
            selection: "#3e4451".into(),
            normal: [
                "#1c1f24".into(),
                "#ff6c6b".into(),
                "#98be65".into(),
                "#da8548".into(),
                "#51afef".into(),
                "#c678dd".into(),
                "#5699af".into(),
                "#202328".into(),
            ],
            bright: [
                "#5b6268".into(),
                "#da8548".into(),
                "#4db5bd".into(),
                "#ecbe7b".into(),
                "#2257a0".into(),
                "#a9a1e1".into(),
                "#46d9ff".into(),
                "#dfdfdf".into(),
            ],
        },
        // ── Witch Hazel ───────────────────────────────────────────────────────
        Theme {
            name: "Witch Hazel".into(),
            background: "#433e56".into(),
            foreground: "#f8f8f2".into(),
            cursor: "#e9c46a".into(),
            selection: "#5b5474".into(),
            normal: [
                "#433e56".into(),
                "#f47067".into(),
                "#74dfc4".into(),
                "#e9c46a".into(),
                "#b8a9d9".into(),
                "#c0a4f3".into(),
                "#95c4ec".into(),
                "#f8f8f2".into(),
            ],
            bright: [
                "#716898".into(),
                "#ff8099".into(),
                "#a8edcc".into(),
                "#f1d79e".into(),
                "#d3c1e9".into(),
                "#d4bcfc".into(),
                "#b2d6f5".into(),
                "#ffffff".into(),
            ],
        },
        // ── Iceberg ───────────────────────────────────────────────────────────
        Theme {
            name: "Iceberg Dark".into(),
            background: "#161821".into(),
            foreground: "#d2d4de".into(),
            cursor: "#c6c8d1".into(),
            selection: "#1e2132".into(),
            normal: [
                "#1e2132".into(),
                "#e27878".into(),
                "#b4be82".into(),
                "#e2a478".into(),
                "#84a0c6".into(),
                "#a093c7".into(),
                "#89b8c2".into(),
                "#c6c8d1".into(),
            ],
            bright: [
                "#6b7089".into(),
                "#e98989".into(),
                "#c0ca8e".into(),
                "#e9b189".into(),
                "#91acd1".into(),
                "#ada0d3".into(),
                "#95c4ce".into(),
                "#d2d4de".into(),
            ],
        },
        // ── Penumbra ──────────────────────────────────────────────────────────
        Theme {
            name: "Penumbra Dark".into(),
            background: "#1e1e1e".into(),
            foreground: "#dedcd8".into(),
            cursor: "#dedcd8".into(),
            selection: "#2c2c2c".into(),
            normal: [
                "#2c2c2c".into(),
                "#f28779".into(),
                "#a8b36a".into(),
                "#f9c84d".into(),
                "#82b4d4".into(),
                "#d49ac6".into(),
                "#73ccce".into(),
                "#a6a392".into(),
            ],
            bright: [
                "#767166".into(),
                "#ff9b8b".into(),
                "#bdd071".into(),
                "#ffe06e".into(),
                "#97cfe8".into(),
                "#e8b4da".into(),
                "#88e0e0".into(),
                "#dedcd8".into(),
            ],
        },
        // ── Sonokai ───────────────────────────────────────────────────────────
        Theme {
            name: "Sonokai".into(),
            background: "#2c2e34".into(),
            foreground: "#e2e2e3".into(),
            cursor: "#e2e2e3".into(),
            selection: "#3d3f4b".into(),
            normal: [
                "#181819".into(),
                "#fc5d7c".into(),
                "#9ed072".into(),
                "#e7c664".into(),
                "#76cce0".into(),
                "#b39df3".into(),
                "#f39660".into(),
                "#e2e2e3".into(),
            ],
            bright: [
                "#7f8490".into(),
                "#fc5d7c".into(),
                "#9ed072".into(),
                "#e7c664".into(),
                "#76cce0".into(),
                "#b39df3".into(),
                "#f39660".into(),
                "#e2e2e3".into(),
            ],
        },
        // ── Srcery ────────────────────────────────────────────────────────────
        Theme {
            name: "Srcery".into(),
            background: "#1c1b19".into(),
            foreground: "#fce8c3".into(),
            cursor: "#fbb829".into(),
            selection: "#3e3b32".into(),
            normal: [
                "#1c1b19".into(),
                "#ef2f27".into(),
                "#519f50".into(),
                "#fbb829".into(),
                "#2c78bf".into(),
                "#e02c6d".into(),
                "#0aaeb3".into(),
                "#baa67f".into(),
            ],
            bright: [
                "#918175".into(),
                "#f75341".into(),
                "#98bc37".into(),
                "#fed06e".into(),
                "#68a8e4".into(),
                "#ff5c8f".into(),
                "#2be4d0".into(),
                "#fce8c3".into(),
            ],
        },
        // ── Zenbones ──────────────────────────────────────────────────────────
        Theme {
            name: "Zenbones Dark".into(),
            background: "#1c1917".into(),
            foreground: "#cfc1b3".into(),
            cursor: "#cfc1b3".into(),
            selection: "#2c2825".into(),
            normal: [
                "#2c2825".into(),
                "#de6e7c".into(),
                "#819b69".into(),
                "#b77e64".into(),
                "#6099c0".into(),
                "#b279a7".into(),
                "#66a5ad".into(),
                "#a09a92".into(),
            ],
            bright: [
                "#6e6862".into(),
                "#e8838f".into(),
                "#8aac76".into(),
                "#c18f78".into(),
                "#61abda".into(),
                "#cf86be".into(),
                "#65b8c1".into(),
                "#cfc1b3".into(),
            ],
        },
        // ── Embark ────────────────────────────────────────────────────────────
        Theme {
            name: "Embark".into(),
            background: "#1e1c31".into(),
            foreground: "#cbe3e7".into(),
            cursor: "#ffe9aa".into(),
            selection: "#3e3859".into(),
            normal: [
                "#100e23".into(),
                "#f48fb1".into(),
                "#a1efd3".into(),
                "#ffe9aa".into(),
                "#91ddff".into(),
                "#d4bfff".into(),
                "#87dfeb".into(),
                "#cbe3e7".into(),
            ],
            bright: [
                "#585273".into(),
                "#f48fb1".into(),
                "#a1efd3".into(),
                "#ffe9aa".into(),
                "#91ddff".into(),
                "#d4bfff".into(),
                "#87dfeb".into(),
                "#cbe3e7".into(),
            ],
        },
        // ── Tender ────────────────────────────────────────────────────────────
        Theme {
            name: "Tender".into(),
            background: "#282828".into(),
            foreground: "#eeeeee".into(),
            cursor: "#eeeeee".into(),
            selection: "#424242".into(),
            normal: [
                "#282828".into(),
                "#f43841".into(),
                "#c9d05c".into(),
                "#d3b987".into(),
                "#73cef4".into(),
                "#ee40fb".into(),
                "#73cef4".into(),
                "#eeeeee".into(),
            ],
            bright: [
                "#888888".into(),
                "#f43841".into(),
                "#c9d05c".into(),
                "#d3b987".into(),
                "#73cef4".into(),
                "#ee40fb".into(),
                "#73cef4".into(),
                "#ffffff".into(),
            ],
        },
        // ── Spacemacs Dark ────────────────────────────────────────────────────
        Theme {
            name: "Spacemacs Dark".into(),
            background: "#1f2022".into(),
            foreground: "#b2b2b2".into(),
            cursor: "#e3dedd".into(),
            selection: "#292e34".into(),
            normal: [
                "#292e34".into(),
                "#f2241f".into(),
                "#67b11d".into(),
                "#b1951d".into(),
                "#4f97d7".into(),
                "#a31db1".into(),
                "#28def0".into(),
                "#b2b2b2".into(),
            ],
            bright: [
                "#585858".into(),
                "#f2241f".into(),
                "#67b11d".into(),
                "#b1951d".into(),
                "#4f97d7".into(),
                "#a31db1".into(),
                "#28def0".into(),
                "#e8e8e8".into(),
            ],
        },
        // ── Nightfox ──────────────────────────────────────────────────────────
        Theme {
            name: "Nightfox".into(),
            background: "#192330".into(),
            foreground: "#cdcecf".into(),
            cursor: "#cdcecf".into(),
            selection: "#2b3b51".into(),
            normal: [
                "#393b44".into(),
                "#c94f6d".into(),
                "#81b29a".into(),
                "#dbc074".into(),
                "#719cd6".into(),
                "#9d79d6".into(),
                "#63cdcf".into(),
                "#dfdfe0".into(),
            ],
            bright: [
                "#575860".into(),
                "#d16983".into(),
                "#8ebaa4".into(),
                "#e0c989".into(),
                "#86abdc".into(),
                "#baa1e2".into(),
                "#7ad4d6".into(),
                "#e4e4e5".into(),
            ],
        },
        Theme {
            name: "Carbonfox".into(),
            background: "#161616".into(),
            foreground: "#f2f4f8".into(),
            cursor: "#33b1ff".into(),
            selection: "#2a2a2a".into(),
            normal: [
                "#282828".into(),
                "#ee5396".into(),
                "#25be6a".into(),
                "#08bdba".into(),
                "#78a9ff".into(),
                "#be95ff".into(),
                "#33b1ff".into(),
                "#dde1e6".into(),
            ],
            bright: [
                "#484848".into(),
                "#f16da6".into(),
                "#46c880".into(),
                "#2dc7c4".into(),
                "#a4c2f4".into(),
                "#d0acff".into(),
                "#66c2ff".into(),
                "#f2f4f8".into(),
            ],
        },
        // ── Miramare ──────────────────────────────────────────────────────────
        Theme {
            name: "Miramare".into(),
            background: "#0a0e14".into(),
            foreground: "#cbccc6".into(),
            cursor: "#f28779".into(),
            selection: "#1a2634".into(),
            normal: [
                "#0a0e14".into(),
                "#f28779".into(),
                "#bae67e".into(),
                "#ffd580".into(),
                "#5ccfe6".into(),
                "#d4bfff".into(),
                "#95e6cb".into(),
                "#cbccc6".into(),
            ],
            bright: [
                "#607080".into(),
                "#f28779".into(),
                "#bae67e".into(),
                "#ffd580".into(),
                "#5ccfe6".into(),
                "#d4bfff".into(),
                "#95e6cb".into(),
                "#ffffff".into(),
            ],
        },
        // ── VS Code Dark+ ─────────────────────────────────────────────────────
        Theme {
            name: "VS Code Dark+".into(),
            background: "#1e1e1e".into(),
            foreground: "#d4d4d4".into(),
            cursor: "#aeafad".into(),
            selection: "#264f78".into(),
            normal: [
                "#1e1e1e".into(),
                "#f14c4c".into(),
                "#23d18b".into(),
                "#f5f543".into(),
                "#3b8eea".into(),
                "#bc3fbc".into(),
                "#29b8db".into(),
                "#e5e5e5".into(),
            ],
            bright: [
                "#666666".into(),
                "#f1897f".into(),
                "#23d18b".into(),
                "#f5f543".into(),
                "#3b8eea".into(),
                "#d670d6".into(),
                "#29b8db".into(),
                "#e5e5e5".into(),
            ],
        },
        // ── Xcode ─────────────────────────────────────────────────────────────
        Theme {
            name: "Xcode Dark".into(),
            background: "#1f1f24".into(),
            foreground: "#d9d9d9".into(),
            cursor: "#d9d9d9".into(),
            selection: "#2f3b4e".into(),
            normal: [
                "#414453".into(),
                "#ff7f7f".into(),
                "#acf2a5".into(),
                "#ffa14f".into(),
                "#6bdfff".into(),
                "#ff85ff".into(),
                "#a3f7ff".into(),
                "#d9d9d9".into(),
            ],
            bright: [
                "#8f8f9b".into(),
                "#ff9f9f".into(),
                "#c3f2be".into(),
                "#ffb76f".into(),
                "#8bdfff".into(),
                "#ff9fff".into(),
                "#c3f7ff".into(),
                "#ffffff".into(),
            ],
        },
        // ── Pastel colors ─────────────────────────────────────────────────────
        Theme {
            name: "Pastel Dark".into(),
            background: "#2f3640".into(),
            foreground: "#f5f6fa".into(),
            cursor: "#f5f6fa".into(),
            selection: "#424858".into(),
            normal: [
                "#2f3640".into(),
                "#e84393".into(),
                "#00d2d3".into(),
                "#feca57".into(),
                "#48dbfb".into(),
                "#ff9ff3".into(),
                "#54a0ff".into(),
                "#dfe6e9".into(),
            ],
            bright: [
                "#636e72".into(),
                "#fd79a8".into(),
                "#55efc4".into(),
                "#fdcb6e".into(),
                "#74b9ff".into(),
                "#a29bfe".into(),
                "#81ecec".into(),
                "#ffffff".into(),
            ],
        },
        // ── Oxocarbon ─────────────────────────────────────────────────────────
        Theme {
            name: "Oxocarbon Dark".into(),
            background: "#161616".into(),
            foreground: "#f2f4f8".into(),
            cursor: "#78a9ff".into(),
            selection: "#393939".into(),
            normal: [
                "#262626".into(),
                "#ff7eb6".into(),
                "#42be65".into(),
                "#ffe97b".into(),
                "#82cfff".into(),
                "#be95ff".into(),
                "#3ddbd9".into(),
                "#dde1e6".into(),
            ],
            bright: [
                "#393939".into(),
                "#ff7eb6".into(),
                "#42be65".into(),
                "#ffe97b".into(),
                "#82cfff".into(),
                "#be95ff".into(),
                "#3ddbd9".into(),
                "#ffffff".into(),
            ],
        },
        // ── Cyberpunk ─────────────────────────────────────────────────────────
        Theme {
            name: "Cyberpunk".into(),
            background: "#000b1e".into(),
            foreground: "#ffffff".into(),
            cursor: "#00ffff".into(),
            selection: "#003366".into(),
            normal: [
                "#000b1e".into(),
                "#ff0055".into(),
                "#00ffaa".into(),
                "#ffcc00".into(),
                "#00ccff".into(),
                "#ff00aa".into(),
                "#00ffff".into(),
                "#cccccc".into(),
            ],
            bright: [
                "#336699".into(),
                "#ff3377".into(),
                "#33ffcc".into(),
                "#ffdd44".into(),
                "#33ddff".into(),
                "#ff33cc".into(),
                "#33ffff".into(),
                "#ffffff".into(),
            ],
        },
        // ── Synthwave ─────────────────────────────────────────────────────────
        Theme {
            name: "Synthwave".into(),
            background: "#262335".into(),
            foreground: "#ffffff".into(),
            cursor: "#f97e72".into(),
            selection: "#495495".into(),
            normal: [
                "#495495".into(),
                "#f97e72".into(),
                "#72f1b8".into(),
                "#fede5d".into(),
                "#36f9f6".into(),
                "#e1acff".into(),
                "#03edf9".into(),
                "#ffffff".into(),
            ],
            bright: [
                "#6273a6".into(),
                "#fe4450".into(),
                "#72f1b8".into(),
                "#f97e72".into(),
                "#36f9f6".into(),
                "#e1acff".into(),
                "#03edf9".into(),
                "#ffffff".into(),
            ],
        },
        // ── Outrun Dark ───────────────────────────────────────────────────────
        Theme {
            name: "Outrun Dark".into(),
            background: "#00002a".into(),
            foreground: "#d0d0fa".into(),
            cursor: "#d0d0fa".into(),
            selection: "#190235".into(),
            normal: [
                "#00002a".into(),
                "#ff4242".into(),
                "#59f176".into(),
                "#f3e877".into(),
                "#66b0ff".into(),
                "#f10596".into(),
                "#0ef0f0".into(),
                "#d0d0fa".into(),
            ],
            bright: [
                "#4d4dff".into(),
                "#ff4242".into(),
                "#59f176".into(),
                "#f3e877".into(),
                "#66b0ff".into(),
                "#f10596".into(),
                "#0ef0f0".into(),
                "#ffffff".into(),
            ],
        },
        // ── Fairy Floss ───────────────────────────────────────────────────────
        Theme {
            name: "Fairy Floss".into(),
            background: "#5a5475".into(),
            foreground: "#f8f8f0".into(),
            cursor: "#ffe9aa".into(),
            selection: "#716799".into(),
            normal: [
                "#464258".into(),
                "#ff857f".into(),
                "#a8ce93".into(),
                "#ffe9aa".into(),
                "#6dfedf".into(),
                "#fd9353".into(),
                "#c5a3ff".into(),
                "#f8f8f0".into(),
            ],
            bright: [
                "#716799".into(),
                "#ff857f".into(),
                "#a8ce93".into(),
                "#ffe9aa".into(),
                "#6dfedf".into(),
                "#fd9353".into(),
                "#c5a3ff".into(),
                "#ffffff".into(),
            ],
        },
        // ── Alabaster ─────────────────────────────────────────────────────────
        Theme {
            name: "Alabaster Dark".into(),
            background: "#0e1415".into(),
            foreground: "#cecece".into(),
            cursor: "#cecece".into(),
            selection: "#1a2426".into(),
            normal: [
                "#0e1415".into(),
                "#cd3131".into(),
                "#00a150".into(),
                "#d4ac0a".into(),
                "#4078f2".into(),
                "#a626a4".into(),
                "#0997b3".into(),
                "#cecece".into(),
            ],
            bright: [
                "#535353".into(),
                "#f14c4c".into(),
                "#23d18b".into(),
                "#f5f543".into(),
                "#3b8eea".into(),
                "#d670d6".into(),
                "#29b8db".into(),
                "#ffffff".into(),
            ],
        },
        // ── Arcoiris ──────────────────────────────────────────────────────────
        Theme {
            name: "Arcoiris Dark".into(),
            background: "#1a1a2e".into(),
            foreground: "#e0e0e0".into(),
            cursor: "#e040fb".into(),
            selection: "#2a2a4e".into(),
            normal: [
                "#1a1a2e".into(),
                "#f44747".into(),
                "#6be67e".into(),
                "#f7d96a".into(),
                "#569cd6".into(),
                "#c678dd".into(),
                "#56c7d1".into(),
                "#e0e0e0".into(),
            ],
            bright: [
                "#4a4a6e".into(),
                "#ff6b6b".into(),
                "#98e4a3".into(),
                "#fbe992".into(),
                "#7ec8e3".into(),
                "#daa4f4".into(),
                "#81d4da".into(),
                "#ffffff".into(),
            ],
        },
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_has_at_least_fifty_themes() {
        assert!(
            catalog_themes().len() >= 50,
            "catalog must contain at least 50 themes, got {}",
            catalog_themes().len()
        );
    }

    #[test]
    fn catalog_names_are_unique() {
        let themes = catalog_themes();
        let mut seen = std::collections::HashSet::new();
        for t in &themes {
            assert!(
                seen.insert(t.name.as_str()),
                "duplicate catalog theme name: {:?}",
                t.name
            );
        }
    }

    #[test]
    fn no_catalog_theme_has_all_zero_palette() {
        for theme in catalog_themes() {
            let r = theme.resolved();
            // Background, foreground, and cursor must not all be zero at once.
            let all_zero =
                r.background == [0, 0, 0] && r.foreground == [0, 0, 0] && r.cursor == [0, 0, 0];
            assert!(
                !all_zero,
                "theme {:?} has all-zero background/foreground/cursor",
                r.name
            );
            // Every normal and bright colour must not be exactly [0,0,0] for
            // all 8 slots simultaneously.
            let normals_zero = r.normal.iter().all(|c| *c == [0u8, 0u8, 0u8]);
            let brights_zero = r.bright.iter().all(|c| *c == [0u8, 0u8, 0u8]);
            assert!(
                !normals_zero,
                "theme {:?} has all-zero normal palette",
                r.name
            );
            assert!(
                !brights_zero,
                "theme {:?} has all-zero bright palette",
                r.name
            );
        }
    }

    #[test]
    fn all_catalog_themes_resolve_without_panic() {
        for theme in catalog_themes() {
            let _ = theme.resolved();
        }
    }

    #[test]
    fn catalog_theme_hex_strings_are_valid() {
        for theme in catalog_themes() {
            let r = theme.resolved();
            // If any hex was invalid, parse_hex returns None and the fallback
            // is a Tokyo Night default — meaning bg would be #0d1017.
            // We can at least assert the name is non-empty as a basic sanity.
            assert!(!r.name.is_empty(), "resolved theme name must be non-empty");
        }
    }
}
